/**
 * Re-export all hooks from optimistic version with automatic retry and error handling
 * This provides a single import point for all data fetching hooks
 */
export {
  QUERY_KEYS,
  useClientes,
  useCreateCliente,
  useUpdateCliente,
  useDeleteCliente,
  useVendas,
  useProdutos,
  useCreateProduto,
  useUpdateProduto,
  useDeleteProduto,
  useEstoque,
  useUpdateEstoque,
  useVendedores,
  useCreateVendedor,
  useUpdateVendedor,
  useDeleteVendedor,
  useFornecedores,
  useCreateFornecedor,
  useUpdateFornecedor,
  useDeleteFornecedor,
  useCaixaAberto,
  useContasPagar,
  useResumoPagar,
  useCreateContaPagar,
  useDeleteContaPagar,
  useContasReceber,
  useResumoReceber,
  useCreateContaReceber,
  useDeleteContaReceber,
  useCategoriasFinanceiras,
  useInvalidateQueries,
} from './useQueryCacheOptimistic';
